import express from 'express';
import fs from 'fs';
import pino from 'pino';
import { makeWASocket, useMultiFileAuthState, delay, Browsers, jidNormalizedUser, fetchLatestBaileysVersion, DisconnectReason } from '@vreden/meta';
import pn from 'awesome-phonenumber';

const router = express.Router();

function removeFile(FilePath) {
    try {
        if (!fs.existsSync(FilePath)) return false;
        fs.rmSync(FilePath, { recursive: true, force: true });
    } catch (e) {
        console.error('Error removing file:', e);
    }
}

router.get('/', async (req, res) => {
    let requestFinished = false;

    const safeSend = (statusCode, payload) => {
        if (requestFinished || res.headersSent) return;
        requestFinished = true;
        res.status(statusCode).send(payload);
    };

    const requestTimeout = setTimeout(() => {
        safeSend(504, { code: 'Timed out waiting for WhatsApp pairing code. Please try again.' });
    }, 35000);

    let num = req.query.number;
    if (!num) {
        clearTimeout(requestTimeout);
        return safeSend(400, {
            code: 'Phone number is required. Pass it as ?number=2367012345678'
        });
    }
    let dirs = './' + (num || `session`);

    await removeFile(dirs);

    num = num.replace(/[^0-9]/g, '');

    const phone = pn('+' + num);
    if (!phone.isValid()) {
        if (!res.headersSent) {
            clearTimeout(requestTimeout);
            return safeSend(400, { code: 'Invalid phone number. Please enter your full international number (e.g., 263701234567) without + or spaces.' });
        }
        return;
    }
    num = phone.getNumber('e164').replace('+', '');

    async function initiateSession() {
        const { state, saveCreds } = await useMultiFileAuthState(dirs);

        try {
            const { version, isLatest } = await fetchLatestBaileysVersion();
            let jailbreakBot = makeWASocket({
                version,
                auth: state,
                printQRInTerminal: false,
                logger: pino({ level: "fatal" }).child({ level: "fatal" }),
                browser: Browsers.windows('Chrome'),
                markOnlineOnConnect: false,
                generateHighQualityLinkPreview: false,
                defaultQueryTimeoutMs: 60000,
                connectTimeoutMs: 60000,
                keepAliveIntervalMs: 30000,
                retryRequestDelayMs: 250,
                maxRetries: 5,
            });

            jailbreakBot.ev.on('connection.update', async (update) => {
                const { connection, lastDisconnect, isNewLogin, isOnline } = update;

                if (connection === 'open') {
                    console.log("✅ Connected successfully!");
                    console.log("📱 Sending session file to user...");
                    
                    try {
                        const sessionKnight = fs.readFileSync(dirs + '/creds.json');

                        const userJid = jidNormalizedUser(num + '@s.whatsapp.net');
                        await jailbreakBot.sendMessage(userJid, {
                            document: sessionKnight,
                            mimetype: 'application/json',
                            fileName: 'creds.json'
                        });
                        console.log("📄 Session file sent successfully");

                        await jailbreakBot.sendMessage(userJid, {
                            text: `⚠️ Do not share this file with anybody. It gives full access to your whatsapp. ⚠️\n\nGenerated by JAILBREAK session linker.`
                        });
                        console.log("⚠️ Security warning sent successfully");

                        console.log("🧹 Cleaning up session...");
                        await delay(1000);
                        removeFile(dirs);
                        console.log("✅ Session cleaned up successfully");
                        console.log("🎉 Process completed successfully!");
                    } catch (error) {
                        console.error("❌ Error sending messages:", error);
                        removeFile(dirs);
                    }
                }

                if (isNewLogin) {
                    console.log("🔐 New login via pair code");
                }

                if (isOnline) {
                    console.log("📶 Client is online");
                }

                if (connection === 'close') {
                    const statusCode = lastDisconnect?.error?.output?.statusCode;
                    const shouldReconnect = statusCode !== DisconnectReason.loggedOut;

                    if (!state.creds.registered) {
                        clearTimeout(requestTimeout);
                        safeSend(503, { code: 'Connection closed before pairing code was generated. Please try again.' });
                        removeFile(dirs);
                        return;
                    }

                    if (!shouldReconnect || statusCode === 401) {
                        console.log("❌ Logged out from WhatsApp. Need to generate new pair code.");
                    } else {
                        console.log("🔁 Connection closed — restarting...");
                        initiateSession();
                    }
                }
            });

            if (!state.creds.registered) {
                await delay(3000);
                num = num.replace(/[^\d+]/g, '');
                if (num.startsWith('+')) num = num.substring(1);

                try {
                    let code = await jailbreakBot.requestPairingCode(num);
                    code = code?.match(/.{1,4}/g)?.join('-') || code;
                    if (!res.headersSent) {
                        console.log({ num, code });
                        clearTimeout(requestTimeout);
                        safeSend(200, { code });
                    }
                } catch (error) {
                    console.error('Error requesting pairing code:', error);
                    clearTimeout(requestTimeout);
                    safeSend(503, { code: 'Failed to get pairing code. Please check your phone number and try again.' });
                }
            }

            jailbreakBot.ev.on('creds.update', saveCreds);
        } catch (err) {
            console.error('Error initializing session:', err);
            clearTimeout(requestTimeout);
            safeSend(503, { code: 'Service Unavailable' });
        }
    }

    await initiateSession();

    if (!requestFinished) {
        // keep timeout active while socket negotiation is in flight
    }
});

process.on('uncaughtException', (err) => {
    let e = String(err);
    if (e.includes("conflict")) return;
    if (e.includes("not-authorized")) return;
    if (e.includes("Socket connection timeout")) return;
    if (e.includes("rate-overlimit")) return;
    if (e.includes("Connection Closed")) return;
    if (e.includes("Timed Out")) return;
    if (e.includes("Value not found")) return;
    if (e.includes("Stream Errored")) return;
    if (e.includes("Stream Errored (restart required)")) return;
    if (e.includes("statusCode: 515")) return;
    if (e.includes("statusCode: 503")) return;
    console.log('Caught exception: ', err);
});

export default router;
